### ISSUE TITLE
lib-makefiles

### ISSUE THREAD

**Issue by ltclm** [geoadmin/template-service-flask#10]
We have tried, some time ago to centralize some Makefile commands in this repository:
https://github.com/geoadmin/lib-makefiles

theres probably something we could use here too.

**Comment by ltkum** [comment]
I started the template by using the lib makefiles, but after discussion, we tought it would be best to avoid too much dependencies from submodules, Especially since we removed most of docker functions from the makefile to ask codebuild to build and push images.

codebuild also sometimes has difficulty with submodules, but I am open to the idea of using lib-makefiles if we need some functions that were already implemented and could help make the makefile easier to read.

**Comment by ltshb** [comment]
In my opinion we should in future get rid of the makefile and uses pure python tools like (doit)[https://pydoit.org/] or python [invoke](http://www.pyinvoke.org/) we can then create a python package repository and use it in the micro services and don't have any submodule which are not always loved by developper :-) At the end we can have per micro service a simple python configuration file and all complicated code could be in a central python package.

**Comment by ltclm** [comment]
we have to decide which technology we want to use for this kind of tasks (buid, templating, deploy, tests, ...) and use the same technology in **ALL** projects. not only in the micro services. Actually we have mostly bash and makefile. If we decide to ramp up a 3rd technology, please do this in the other projects too.
