### ISSUE TITLE
buildspec.yml env variables are not available locally

### ISSUE THREAD

**Issue by ltclm** [geoadmin/template-service-flask#14]
In the current solution it is planned to define environment variables in buildspec.yml.
Those variables are not available in the makefile targets when you execute them locally.

It should be possible to use the same makefile targets in codebuild and locally.

**Comment by ltshb** [comment]
I'm not sure I understand the issue here, could you describe the issue with and example ? Currently the makefile targets can be used locally.

**Comment by ltclm** [comment]
the local makefile is working now (at least in  project infra-geoadmin-tests since the merge of https://github.com/geoadmin/infra-geoadmin-tests/pull/2). 
But we have to define the same env variables twice:
1) Makefile https://github.com/geoadmin/infra-geoadmin-tests/blob/develop/Makefile#L16
2) buildspec.yml https://github.com/geoadmin/infra-geoadmin-tests/blob/develop/buildspec.yml#L5

**Comment by ltshb** [comment]
I think this should not be addressed here because this is just a service template and it doesn't have currently any variable. I suggest to have this directly resolved inside the infra-geoadmin-test repo. 

In my opinion the service repository should not have any environment configuration values, this should be part of the end-to-end testing repository and deployment repository.

So if you are I'll close this issue ?

**Comment by ltclm** [comment]
there are env variables in this template:
https://github.com/geoadmin/template-service-flask/blob/master/buildspec.yml#L5
and the same variable are specified a second time in the Makefile:
https://github.com/geoadmin/template-service-flask/blob/master/Makefile#L12

if thats ok to set them two times, yes we can close this issue.
